version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "cafe"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "5433:5432"